### ISSUE TITLE
CUDA_Compiler_jll does not invalidate when changing CUDA_Runtime_jll's preferences

### ISSUE THREAD

**Issue by benz0li** [JuliaGPU/CUDA.jl#2851]
**Describe the bug**

Executing `CUDA.versioninfo()` on my *reference deployment* results in an error:

```
CUDA toolchain: 
- runtime 12.9, local installation
- driver 570.172.8 for 13.0
ERROR: UndefVarError: `cuda_version` not defined in `CUDA_Compiler_jll`
Suggestion: check for spelling errors or missing imports.
Stacktrace:
 [1] getproperty
   @ ./Base.jl:42 [inlined]
 [2] compiler_version
   @ /usr/local/julia/local/share/julia/packages/CUDA/Wfi8S/lib/cudadrv/version.jl:101 [inlined]
 [3] versioninfo(io::Base.TTY)
   @ CUDA /usr/local/julia/local/share/julia/packages/CUDA/Wfi8S/src/utilities.jl:58
 [4] versioninfo()
   @ CUDA /usr/local/julia/local/share/julia/packages/CUDA/Wfi8S/src/utilities.jl:42
 [5] top-level scope
   @ REPL[2]:1
```

This happened using docker image `glcr.b-data.ch/jupyterlab/cuda/julia/base:1.11.6`[^1] when it was based on CUDA 12[.9.1].  
ℹ️ It worked fine with CUDA.ja v5.8.2

[^1]: This docker image has been updated to CUDA 13[.0.0] in the meantime.

**To reproduce**

To reproduce with container image `glcr.b-data.ch/jupyterlab/cuda/julia/base:1.11.6` based on CUDA 13[.0.0]:

On a Linux host with Docker installed:

```shell
docker run --rm --gpus all -ti glcr.b-data.ch/jupyterlab/cuda/julia/base:1.11.6 bash
```

In the container:

```shell
julia
```

```julia
CUDA.versioninfo()
```

```
CUDA toolchain: 
- runtime 13.0, local installation
- driver 570.172.8 for 13.0
ERROR: UndefVarError: `cuda_version` not defined in `CUDA_Compiler_jll`
Suggestion: check for spelling errors or missing imports.
Stacktrace:
 [1] getproperty
   @ ./Base.jl:42 [inlined]
 [2] compiler_version
   @ /usr/local/julia/local/share/julia/packages/CUDA/Wfi8S/lib/cudadrv/version.jl:101 [inlined]
 [3] versioninfo(io::Base.TTY)
   @ CUDA /usr/local/julia/local/share/julia/packages/CUDA/Wfi8S/src/utilities.jl:58
 [4] versioninfo()
   @ CUDA /usr/local/julia/local/share/julia/packages/CUDA/Wfi8S/src/utilities.jl:42
 [5] top-level scope
   @ REPL[1]:1
```

**Expected behavior**

That this command executes successfully and prints all output.

**Version info**

Details on Julia:

```
versioninfo()
```

```
Julia Version 1.11.6
Commit 9615af0f269 (2025-07-09 12:58 UTC)
Build Info:
  Official https://julialang.org/ release
Platform Info:
  OS: Linux (x86_64-linux-gnu)
  CPU: 40 × Intel(R) Xeon(R) Silver 4210R CPU @ 2.40GHz
  WORD_SIZE: 64
  LLVM: libLLVM-16.0.6 (ORCJIT, cascadelake)
Threads: 1 default, 0 interactive, 1 GC (on 40 virtual cores)
Environment:
  JULIA_VERSION = 1.11.6
  JULIA_PATH = /usr/local/julia
  LD_LIBRARY_PATH = /usr/local/nvidia/lib:/usr/local/nvidia/lib64:/usr/local/cuda/lib64
```

Details on CUDA:

```
CUDA.versioninfo()
```

👉 This command does not execute successfully.

**Additional context**

Linux Host:

```shell
cat /etc/os-release
```

```
PRETTY_NAME="Debian GNU/Linux 12 (bookworm)"
NAME="Debian GNU/Linux"
VERSION_ID="12"
VERSION="12 (bookworm)"
VERSION_CODENAME=bookworm
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
```

```shell
nvidia-smi
```

```
Mon Aug 25 09:50:57 2025       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 570.172.08             Driver Version: 570.172.08     CUDA Version: 12.8     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  Quadro RTX 4000                On  |   00000000:AF:00.0 Off |                  N/A |
| 30%   43C    P8              8W /  125W |       1MiB /   8192MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+------------------------+----------------------+
                                                                                         
+-----------------------------------------------------------------------------------------+
| Processes:                                                                              |
|  GPU   GI   CI              PID   Type   Process name                        GPU Memory |
|        ID   ID                                                               Usage      |
|=========================================================================================|
|  No running processes found                                                             |
+-----------------------------------------------------------------------------------------+
```

In the container:

```shell
cat /etc/os-release
```

```
PRETTY_NAME="Ubuntu 24.04.3 LTS"
NAME="Ubuntu"
VERSION_ID="24.04"
VERSION="24.04.3 LTS (Noble Numbat)"
VERSION_CODENAME=noble
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=noble
LOGO=ubuntu-logo
```

```julia
julia -E 'CUDA.functional()'
```

```
...
true
```

**Comment by vchuravy** [comment]
The failing code was introduced by #2801 and might be missing an `@isdefined` check for that global.

Can I ask for your `]status -m` (in particular which version of CUDA_Compiler_jll) and what `CUDA_Compiler_jll.host_platform` yields?

**Comment by benz0li** [comment]
> Can I ask for your `]status -m` (in particular which version of CUDA_Compiler_jll)

CUDA_Compiler_jll v0.2.0+1[^1]

[^1]: See also https://gitlab.b-data.ch/cuda/julia/base/-/jobs/196906

> and what `CUDA_Compiler_jll.host_platform` yields?

Linux x86_64 {cuda=none, cxxstring_abi=cxx11, julia_version=1.11.6, libc=glibc, libgfortran_version=5.0.0, libstdcxx_version=3.4.30}

**Comment by benz0li** [comment]
What surprises me:

```
...
- driver 570.172.8 for 13.0
...
```

NVIDIA driver 570.172.8 is for CUDA 12.9.1[^1]

[^1]: See also https://docs.nvidia.com/cuda/archive/12.9.1/cuda-toolkit-release-notes/index.html

**Comment by vchuravy** [comment]
> Linux x86_64 {cuda=none

Oo that is not great... That means we failed to detect CUDA.

https://github.com/JuliaBinaryWrappers/CUDA_Compiler_jll.jl/blob/e5ab8d9ea21dc1119f4ebf72e388b0e085f03029/.pkg/platform_augmentation.jl#L135

Can you do `JULIA_DEBUG=CUDA_Compiler_jll`

**Comment by benz0li** [comment]
> Can you do `JULIA_DEBUG=CUDA_Compiler_jll`

Output is the same.

**Comment by benz0li** [comment]
@vchuravy You may debug/test yourself at https://demo.cuda.jupyter.b-data.ch.  
ℹ️ Login with your GitHub account.

Select image `[CUDA 13] Julia 1.11 + Python 3.13 (jupyterlab/cuda/julia/pubtools:latest)`.

**Comment by benz0li** [comment]
Output after

```
export JULIA_DEBUG=CUDA_Runtime_Discovery
julia
```

```
Executing site-specific startup file (/usr/local/julia/etc/julia/startup.jl)...
Executing user-specific startup file (/home/jovyan/.julia/config/startup.jl)...
Revise started
┌ Debug: Looking for CUDA toolkit via environment variables CUDA_HOME
└ @ CUDA_Runtime_Discovery /usr/local/julia/local/share/julia/packages/CUDA_Runtime_Discovery/8SKfu/src/CUDA_Runtime_Discovery.jl:318
┌ Debug: Looking for binary compute-sanitizer in /usr/local/cuda or /usr/local/cuda/extras/compute-sanitizer or /usr/local/cuda/compute-sanitizer
│   all_locations =
│    6-element Vector{String}:
│     "/usr/local/cuda"
│     "/usr/local/cuda/bin"
│     "/usr/local/cuda/extras/compute-sanitizer"
│     "/usr/local/cuda/extras/compute-sanitizer/bin"
│     "/usr/local/cuda/compute-sanitizer"
│     "/usr/local/cuda/compute-sanitizer/bin"
└ @ CUDA_Runtime_Discovery /usr/local/julia/local/share/julia/packages/CUDA_Runtime_Discovery/8SKfu/src/CUDA_Runtime_Discovery.jl:164
┌ Debug: Found compute-sanitizer at /usr/local/cuda/bin/compute-sanitizer
└ @ CUDA_Runtime_Discovery /usr/local/julia/local/share/julia/packages/CUDA_Runtime_Discovery/8SKfu/src/CUDA_Runtime_Discovery.jl:170
┌ Debug: Looking for library cudart, no specific version, in /usr/local/cuda or /usr/local/cuda/extras/compute-sanitizer or /usr/local/cuda/compute-sanitizer
│   all_names =
│    1-element Vector{String}:
│     "libcudart.so"
│   all_locations =
│    15-element Vector{String}:
│     "/usr/local/cuda"
│     "/usr/local/cuda/lib"
│     "/usr/local/cuda/lib64"
│     "/usr/local/cuda/libx64"
│     "/usr/local/cuda/targets/x86_64-linux/lib"
│     "/usr/local/cuda/extras/compute-sanitizer"
│     ⋮
│     "/usr/local/cuda/compute-sanitizer"
│     "/usr/local/cuda/compute-sanitizer/lib"
│     "/usr/local/cuda/compute-sanitizer/lib64"
│     "/usr/local/cuda/compute-sanitizer/libx64"
│     "/usr/local/cuda/compute-sanitizer/targets/x86_64-linux/lib"
└ @ CUDA_Runtime_Discovery /usr/local/julia/local/share/julia/packages/CUDA_Runtime_Discovery/8SKfu/src/CUDA_Runtime_Discovery.jl:136
┌ Debug: Found libcudart.so at /usr/local/cuda/lib64
└ @ CUDA_Runtime_Discovery /usr/local/julia/local/share/julia/packages/CUDA_Runtime_Discovery/8SKfu/src/CUDA_Runtime_Discovery.jl:145
┌ Debug: Looking for library cufft, no specific version, in /usr/local/cuda or /usr/local/cuda/extras/compute-sanitizer or /usr/local/cuda/compute-sanitizer
│   all_names =
│    1-element Vector{String}:
│     "libcufft.so"
│   all_locations =
│    15-element Vector{String}:
│     "/usr/local/cuda"
│     "/usr/local/cuda/lib"
│     "/usr/local/cuda/lib64"
│     "/usr/local/cuda/libx64"
│     "/usr/local/cuda/targets/x86_64-linux/lib"
│     "/usr/local/cuda/extras/compute-sanitizer"
│     ⋮
│     "/usr/local/cuda/compute-sanitizer"
│     "/usr/local/cuda/compute-sanitizer/lib"
│     "/usr/local/cuda/compute-sanitizer/lib64"
│     "/usr/local/cuda/compute-sanitizer/libx64"
│     "/usr/local/cuda/compute-sanitizer/targets/x86_64-linux/lib"
└ @ CUDA_Runtime_Discovery /usr/local/julia/local/share/julia/packages/CUDA_Runtime_Discovery/8SKfu/src/CUDA_Runtime_Discovery.jl:136
┌ Debug: Found libcufft.so at /usr/local/cuda/lib64
└ @ CUDA_Runtime_Discovery /usr/local/julia/local/share/julia/packages/CUDA_Runtime_Discovery/8SKfu/src/CUDA_Runtime_Discovery.jl:145
┌ Debug: Looking for library cublas, no specific version, in /usr/local/cuda or /usr/local/cuda/extras/compute-sanitizer or /usr/local/cuda/compute-sanitizer
│   all_names =
│    1-element Vector{String}:
│     "libcublas.so"
│   all_locations =
│    15-element Vector{String}:
│     "/usr/local/cuda"
│     "/usr/local/cuda/lib"
│     "/usr/local/cuda/lib64"
│     "/usr/local/cuda/libx64"
│     "/usr/local/cuda/targets/x86_64-linux/lib"
│     "/usr/local/cuda/extras/compute-sanitizer"
│     ⋮
│     "/usr/local/cuda/compute-sanitizer"
│     "/usr/local/cuda/compute-sanitizer/lib"
│     "/usr/local/cuda/compute-sanitizer/lib64"
│     "/usr/local/cuda/compute-sanitizer/libx64"
│     "/usr/local/cuda/compute-sanitizer/targets/x86_64-linux/lib"
└ @ CUDA_Runtime_Discovery /usr/local/julia/local/share/julia/packages/CUDA_Runtime_Discovery/8SKfu/src/CUDA_Runtime_Discovery.jl:136
┌ Debug: Found libcublas.so at /usr/local/cuda/lib64
└ @ CUDA_Runtime_Discovery /usr/local/julia/local/share/julia/packages/CUDA_Runtime_Discovery/8SKfu/src/CUDA_Runtime_Discovery.jl:145
┌ Debug: Looking for library cublasLt, no specific version, in /usr/local/cuda or /usr/local/cuda/extras/compute-sanitizer or /usr/local/cuda/compute-sanitizer
│   all_names =
│    1-element Vector{String}:
│     "libcublasLt.so"
│   all_locations =
│    15-element Vector{String}:
│     "/usr/local/cuda"
│     "/usr/local/cuda/lib"
│     "/usr/local/cuda/lib64"
│     "/usr/local/cuda/libx64"
│     "/usr/local/cuda/targets/x86_64-linux/lib"
│     "/usr/local/cuda/extras/compute-sanitizer"
│     ⋮
│     "/usr/local/cuda/compute-sanitizer"
│     "/usr/local/cuda/compute-sanitizer/lib"
│     "/usr/local/cuda/compute-sanitizer/lib64"
│     "/usr/local/cuda/compute-sanitizer/libx64"
│     "/usr/local/cuda/compute-sanitizer/targets/x86_64-linux/lib"
└ @ CUDA_Runtime_Discovery /usr/local/julia/local/share/julia/packages/CUDA_Runtime_Discovery/8SKfu/src/CUDA_Runtime_Discovery.jl:136
┌ Debug: Found libcublasLt.so.13 at /usr/local/cuda/lib64
└ @ CUDA_Runtime_Discovery /usr/local/julia/local/share/julia/packages/CUDA_Runtime_Discovery/8SKfu/src/CUDA_Runtime_Discovery.jl:145
┌ Debug: Looking for library cusparse, no specific version, in /usr/local/cuda or /usr/local/cuda/extras/compute-sanitizer or /usr/local/cuda/compute-sanitizer
│   all_names =
│    1-element Vector{String}:
│     "libcusparse.so"
│   all_locations =
│    15-element Vector{String}:
│     "/usr/local/cuda"
│     "/usr/local/cuda/lib"
│     "/usr/local/cuda/lib64"
│     "/usr/local/cuda/libx64"
│     "/usr/local/cuda/targets/x86_64-linux/lib"
│     "/usr/local/cuda/extras/compute-sanitizer"
│     ⋮
│     "/usr/local/cuda/compute-sanitizer"
│     "/usr/local/cuda/compute-sanitizer/lib"
│     "/usr/local/cuda/compute-sanitizer/lib64"
│     "/usr/local/cuda/compute-sanitizer/libx64"
│     "/usr/local/cuda/compute-sanitizer/targets/x86_64-linux/lib"
└ @ CUDA_Runtime_Discovery /usr/local/julia/local/share/julia/packages/CUDA_Runtime_Discovery/8SKfu/src/CUDA_Runtime_Discovery.jl:136
┌ Debug: Found libcusparse.so at /usr/local/cuda/lib64
└ @ CUDA_Runtime_Discovery /usr/local/julia/local/share/julia/packages/CUDA_Runtime_Discovery/8SKfu/src/CUDA_Runtime_Discovery.jl:145
┌ Debug: Looking for library cusolver, no specific version, in /usr/local/cuda or /usr/local/cuda/extras/compute-sanitizer or /usr/local/cuda/compute-sanitizer
│   all_names =
│    1-element Vector{String}:
│     "libcusolver.so"
│   all_locations =
│    15-element Vector{String}:
│     "/usr/local/cuda"
│     "/usr/local/cuda/lib"
│     "/usr/local/cuda/lib64"
│     "/usr/local/cuda/libx64"
│     "/usr/local/cuda/targets/x86_64-linux/lib"
│     "/usr/local/cuda/extras/compute-sanitizer"
│     ⋮
│     "/usr/local/cuda/compute-sanitizer"
│     "/usr/local/cuda/compute-sanitizer/lib"
│     "/usr/local/cuda/compute-sanitizer/lib64"
│     "/usr/local/cuda/compute-sanitizer/libx64"
│     "/usr/local/cuda/compute-sanitizer/targets/x86_64-linux/lib"
└ @ CUDA_Runtime_Discovery /usr/local/julia/local/share/julia/packages/CUDA_Runtime_Discovery/8SKfu/src/CUDA_Runtime_Discovery.jl:136
┌ Debug: Found libcusolver.so at /usr/local/cuda/lib64
└ @ CUDA_Runtime_Discovery /usr/local/julia/local/share/julia/packages/CUDA_Runtime_Discovery/8SKfu/src/CUDA_Runtime_Discovery.jl:145
┌ Debug: Looking for library cusolverMg, no specific version, in /usr/local/cuda or /usr/local/cuda/extras/compute-sanitizer or /usr/local/cuda/compute-sanitizer
│   all_names =
│    1-element Vector{String}:
│     "libcusolverMg.so"
│   all_locations =
│    15-element Vector{String}:
│     "/usr/local/cuda"
│     "/usr/local/cuda/lib"
│     "/usr/local/cuda/lib64"
│     "/usr/local/cuda/libx64"
│     "/usr/local/cuda/targets/x86_64-linux/lib"
│     "/usr/local/cuda/extras/compute-sanitizer"
│     ⋮
│     "/usr/local/cuda/compute-sanitizer"
│     "/usr/local/cuda/compute-sanitizer/lib"
│     "/usr/local/cuda/compute-sanitizer/lib64"
│     "/usr/local/cuda/compute-sanitizer/libx64"
│     "/usr/local/cuda/compute-sanitizer/targets/x86_64-linux/lib"
└ @ CUDA_Runtime_Discovery /usr/local/julia/local/share/julia/packages/CUDA_Runtime_Discovery/8SKfu/src/CUDA_Runtime_Discovery.jl:136
┌ Debug: Found libcusolverMg.so at /usr/local/cuda/lib64
└ @ CUDA_Runtime_Discovery /usr/local/julia/local/share/julia/packages/CUDA_Runtime_Discovery/8SKfu/src/CUDA_Runtime_Discovery.jl:145
┌ Debug: Looking for library curand, no specific version, in /usr/local/cuda or /usr/local/cuda/extras/compute-sanitizer or /usr/local/cuda/compute-sanitizer
│   all_names =
│    1-element Vector{String}:
│     "libcurand.so"
│   all_locations =
│    15-element Vector{String}:
│     "/usr/local/cuda"
│     "/usr/local/cuda/lib"
│     "/usr/local/cuda/lib64"
│     "/usr/local/cuda/libx64"
│     "/usr/local/cuda/targets/x86_64-linux/lib"
│     "/usr/local/cuda/extras/compute-sanitizer"
│     ⋮
│     "/usr/local/cuda/compute-sanitizer"
│     "/usr/local/cuda/compute-sanitizer/lib"
│     "/usr/local/cuda/compute-sanitizer/lib64"
│     "/usr/local/cuda/compute-sanitizer/libx64"
│     "/usr/local/cuda/compute-sanitizer/targets/x86_64-linux/lib"
└ @ CUDA_Runtime_Discovery /usr/local/julia/local/share/julia/packages/CUDA_Runtime_Discovery/8SKfu/src/CUDA_Runtime_Discovery.jl:136
┌ Debug: Found libcurand.so at /usr/local/cuda/lib64
└ @ CUDA_Runtime_Discovery /usr/local/julia/local/share/julia/packages/CUDA_Runtime_Discovery/8SKfu/src/CUDA_Runtime_Discovery.jl:145
┌ Debug: Looking for library cupti, no specific version, in /usr/local/cuda or /usr/local/cuda/extras/compute-sanitizer or /usr/local/cuda/compute-sanitizer or /usr/local/cuda/extras/CUPTI
│   all_names =
│    1-element Vector{String}:
│     "libcupti.so"
│   all_locations =
│    20-element Vector{String}:
│     "/usr/local/cuda"
│     "/usr/local/cuda/lib"
│     "/usr/local/cuda/lib64"
│     "/usr/local/cuda/libx64"
│     "/usr/local/cuda/targets/x86_64-linux/lib"
│     "/usr/local/cuda/extras/compute-sanitizer"
│     ⋮
│     "/usr/local/cuda/extras/CUPTI"
│     "/usr/local/cuda/extras/CUPTI/lib"
│     "/usr/local/cuda/extras/CUPTI/lib64"
│     "/usr/local/cuda/extras/CUPTI/libx64"
│     "/usr/local/cuda/extras/CUPTI/targets/x86_64-linux/lib"
└ @ CUDA_Runtime_Discovery /usr/local/julia/local/share/julia/packages/CUDA_Runtime_Discovery/8SKfu/src/CUDA_Runtime_Discovery.jl:136
┌ Debug: Found libcupti.so at /usr/local/cuda/lib64
└ @ CUDA_Runtime_Discovery /usr/local/julia/local/share/julia/packages/CUDA_Runtime_Discovery/8SKfu/src/CUDA_Runtime_Discovery.jl:145
┌ Debug: Looking for library nvperf_host, no specific version, in /usr/local/cuda or /usr/local/cuda/extras/compute-sanitizer or /usr/local/cuda/compute-sanitizer or /usr/local/cuda/extras/CUPTI
│   all_names =
│    1-element Vector{String}:
│     "libnvperf_host.so"
│   all_locations =
│    20-element Vector{String}:
│     "/usr/local/cuda"
│     "/usr/local/cuda/lib"
│     "/usr/local/cuda/lib64"
│     "/usr/local/cuda/libx64"
│     "/usr/local/cuda/targets/x86_64-linux/lib"
│     "/usr/local/cuda/extras/compute-sanitizer"
│     ⋮
│     "/usr/local/cuda/extras/CUPTI"
│     "/usr/local/cuda/extras/CUPTI/lib"
│     "/usr/local/cuda/extras/CUPTI/lib64"
│     "/usr/local/cuda/extras/CUPTI/libx64"
│     "/usr/local/cuda/extras/CUPTI/targets/x86_64-linux/lib"
└ @ CUDA_Runtime_Discovery /usr/local/julia/local/share/julia/packages/CUDA_Runtime_Discovery/8SKfu/src/CUDA_Runtime_Discovery.jl:136
┌ Debug: Found libnvperf_host.so at /usr/local/cuda/lib64
└ @ CUDA_Runtime_Discovery /usr/local/julia/local/share/julia/packages/CUDA_Runtime_Discovery/8SKfu/src/CUDA_Runtime_Discovery.jl:145
┌ Debug: Looking for library nvperf_target, no specific version, in /usr/local/cuda or /usr/local/cuda/extras/compute-sanitizer or /usr/local/cuda/compute-sanitizer or /usr/local/cuda/extras/CUPTI
│   all_names =
│    1-element Vector{String}:
│     "libnvperf_target.so"
│   all_locations =
│    20-element Vector{String}:
│     "/usr/local/cuda"
│     "/usr/local/cuda/lib"
│     "/usr/local/cuda/lib64"
│     "/usr/local/cuda/libx64"
│     "/usr/local/cuda/targets/x86_64-linux/lib"
│     "/usr/local/cuda/extras/compute-sanitizer"
│     ⋮
│     "/usr/local/cuda/extras/CUPTI"
│     "/usr/local/cuda/extras/CUPTI/lib"
│     "/usr/local/cuda/extras/CUPTI/lib64"
│     "/usr/local/cuda/extras/CUPTI/libx64"
│     "/usr/local/cuda/extras/CUPTI/targets/x86_64-linux/lib"
└ @ CUDA_Runtime_Discovery /usr/local/julia/local/share/julia/packages/CUDA_Runtime_Discovery/8SKfu/src/CUDA_Runtime_Discovery.jl:136
┌ Debug: Found libnvperf_target.so at /usr/local/cuda/lib64
└ @ CUDA_Runtime_Discovery /usr/local/julia/local/share/julia/packages/CUDA_Runtime_Discovery/8SKfu/src/CUDA_Runtime_Discovery.jl:145
CUDA functional
CUDA may invalidate Revise: https://github.com/timholy/Revise.jl/issues/746
  Activating new project at `~/.julia/environments/v1.11`
               _
   _       _ _(_)_     |  Documentation: https://docs.julialang.org
  (_)     | (_) (_)    |
   _ _   _| |_  __ _   |  Type "?" for help, "]?" for Pkg help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 1.11.6 (2025-07-09)
 _/ |\__'_|_|_|\__'_|  |  Official https://julialang.org/ release
|__/                   |


```

**Comment by benz0li** [comment]
Output after

```
export JULIA_DEBUG=CUDA_Compiler_jll
julia
```

```
Executing site-specific startup file (/usr/local/julia/etc/julia/startup.jl)...
Executing user-specific startup file (/home/jovyan/.julia/config/startup.jl)...
Revise started
CUDA functional
CUDA may invalidate Revise: https://github.com/timholy/Revise.jl/issues/746
  Activating new project at `~/.julia/environments/v1.11`
               _
   _       _ _(_)_     |  Documentation: https://docs.julialang.org
  (_)     | (_) (_)    |
   _ _   _| |_  __ _   |  Type "?" for help, "]?" for Pkg help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 1.11.6 (2025-07-09)
 _/ |\__'_|_|_|\__'_|  |  Official https://julialang.org/ release
|__/                   |


```

Output in Julia after

```julia
julia> import CUDA_Compiler_jll
```

and after

```julia
julia> CUDA_Compiler_jll.host_platform
Linux x86_64 {cuda=none, cxxstring_abi=cxx11, julia_version=1.11.6, libc=glibc, libgfortran_version=5.0.0, libstdcxx_version=3.4.30}
```

Same output as in https://github.com/JuliaGPU/CUDA.jl/issues/2851#issuecomment-3220608716.

**Comment by benz0li** [comment]
You may reproduce all this at https://demo.cuda.jupyter.b-data.ch/ with image `[CUDA 13] Julia 1.11 + Python 3.13 (jupyterlab/cuda/julia/pubtools:latest)`.  
ℹ️ Login with your GitHub account.

**Comment by benz0li** [comment]
@vchuravy Do you require any further `JULIA_DEBUG` output?

**Comment by maleadt** [comment]
Given that this happens in a Docker container, I'm guessing that this has to do with the Preference you've presumably set (either manually or by calling `CUDA.set_runtime_version!`) not being respected, aka. https://github.com/JuliaGPU/CUDA.jl/issues/2852. This should have been fixed by https://github.com/JuliaRegistries/General/pull/137328.

**Comment by benz0li** [comment]
> This should have been fixed by [JuliaRegistries/General#137328](https://github.com/JuliaRegistries/General/pull/137328)

Image `glcr.b-data.ch/jupyterlab/cuda/julia/base:1.11.6` has CUDA_Compiler_jll v0.2.0+2 installed.  
ℹ️ See https://gitlab.b-data.ch/cuda/julia/base/-/jobs/199175#L1006 ff

The issue still persists.

**Comment by benz0li** [comment]
@maleadt Do I need to adjust https://github.com/b-data/julia-docker-stack/blob/b14ab24d4dbc15b303d50a1bf2f41e513b536dc9/base/latest.Dockerfile#L143-L148 for Julia package CUDA v5.8.3?

I am simply following the steps documented at https://cuda.juliagpu.org/stable/installation/overview/#Using-a-local-CUDA and https://cuda.juliagpu.org/stable/installation/overview/#Precompiling-CUDA.jl-without-CUDA.

**Comment by benz0li** [comment]
@maleadt Please reopen.

**Comment by maleadt** [comment]
@vchuravy Looks like https://github.com/JuliaRegistries/General/pull/137328 didn't fix everything. When CUDA_Compiler_jll/CUDA_Runtime_jll are precompiled in an environment without CUDA, their platform tag is `cuda=none`, as expected. Modifying the CUDA_Runtime_jll preference then doesn't correctly cause CUDA_Compiler_jll to get invalidated, resulting in the `cuda=none` version sticking around at run time.

**Comment by vchuravy** [comment]
I suspect the issue is that with `cuda=none` there is no wrapper file https://github.com/JuliaBinaryWrappers/CUDA_Compiler_jll.jl/tree/e5ab8d9ea21dc1119f4ebf72e388b0e085f03029/src/wrappers

Thus in that case we never execute
```
using CUDA_Driver_jll
using CUDA_Runtime_jll
```

and don't establish the provenance link to the preference.

**Comment by maleadt** [comment]
Hopefully fixed by https://github.com/JuliaPackaging/Yggdrasil/pull/11993

**Comment by benz0li** [comment]
The merge pipeline failed: https://buildkite.com/julialang/yggdrasil/builds/23141/steps/canvas

**Comment by vchuravy** [comment]
https://github.com/JuliaPackaging/Yggdrasil/pull/11986/files#r2319006201

**Comment by vchuravy** [comment]
I will take a look in an hour

**Comment by maleadt** [comment]
https://github.com/JuliaPackaging/Yggdrasil/pull/12001

**Comment by benz0li** [comment]
FYI

```julia
CUDA.versioninfo()
```

now returns

```
CUDA toolchain: 
- runtime 13.0, local installation
- driver 570.172.8 for 13.0
- compiler 13.0

CUDA libraries: 
- CUBLAS: 13.0.0
- CURAND: 10.4.0
- CUFFT: 12.0.0
- CUSOLVER: 12.0.3
- CUSPARSE: 12.6.2
- CUPTI: 2025.3.0 (API 130000.0.0)
- NVML: 12.0.0+570.172.8

Julia packages: 
- CUDA: 5.8.3
- CUDA_Driver_jll: 13.0.0+1
- CUDA_Compiler_jll: 0.2.0+3
- CUDA_Runtime_jll: 0.19.0+0
- CUDA_Runtime_Discovery: 1.0.0

Toolchain:
- Julia: 1.11.6
- LLVM: 16.0.6

Preferences:
- CUDA_Runtime_jll.version: 13.0
- CUDA_Runtime_jll.local: true

1 device:
  0: Quadro RTX 4000 (sm_75, 7.601 GiB / 8.000 GiB available)
```

Thank you!

**Comment by benz0li** [comment]
FYI @rlinfati
